<?php
$settingStyles = ($block->getStyles() === null) ? '' : $block->getStyles();
$symbol = $block->getSymbolCurrency();
$totalAmounts = $block->getCalculateTotals();
?>

<?= /* @noEscape */$settingStyles ?>
<div id='mmm-spentsummary' class='mmm-spentsummary'>
    <div>
        <?= /* @noEscape */__('Detail amounts for account') ?>
        (
        <?= /* @noEscape */$block->getEmailAddress() ?>)
    </div>
    <ul>
        <li>
            <?= /* @noEscape */__('totalOrders') ?>
            <?= /* @noEscape */$symbol ?>
            <?= /* @noEscape */$totalAmounts['totalOrders'] ?>
        </li>
        <li>
            <?= /* @noEscape */__('totalInvoicedOrders') ?>
            <?= /* @noEscape */$symbol ?>
            <?= /* @noEscape */$totalAmounts['totalInvoicedOrders'] ?>
        </li>
        <li>
            <?= /* @noEscape */__('totalCreditmemo') ?>
            <?= /* @noEscape */$symbol ?>
            <?= /* @noEscape */$totalAmounts['totalCreditmemo'] ?>
        </li>
        <li>
            <?= /* @noEscape */__('totalSpent') ?>
            <?= /* @noEscape */$symbol ?>
            <?= /* @noEscape */$totalAmounts['totalSpent'] ?>
        </li>
    </ul>
</div>