<div class="wrapper">
    <div class="profile-card">
        <div class="profile-header">
            <img src="https://media.licdn.com/dms/image/D4E16AQFYS9GBdO4Tpw/profile-displaybackgroundimage-shrink_350_1400/0/1666227513463?e=1681344000&v=beta&t=OGAOBeBJ3Ot_WeZazzfMN-Udrp4fFy3corKrR3xUmGk"
                alt="">
        </div>
        <div class="profile-body">
            <div class="author-img">
                <img src="https://media.licdn.com/dms/image/D4D03AQEkRiYzbT44Xg/profile-displayphoto-shrink_200_200/0/1674238290937?e=1681344000&v=beta&t=Mvk496IjYnJTx3z0536OrHZbMRlIRBqeFNBGiHhhaO4"
                    alt="">
            </div>
            <div class="name">Marucci Maximo</div>
            <div class="intro">
                <p>I am a curious developer and passionate about technology.
                </p>
            </div>
            <div class="social-icon">
                <ul>
                    <li>
                        <a href="https://www.linkedin.com/in/marucci-maximo/" target="_blank">
                            <i class="fab fa-linkedin-in"></i>
                        </a>
                    </li>
                    <li>
                        <a href="https://github.com/mmaximo33" target="_blank">
                            <i class="fab fa-github"></i>
                        </a>
                    </li>
                    <li>
                        <a href="https://gitlab.com/marucci.maximo" target="_blank">
                            <i class="fab fa-gitlab"></i>
                        </a>
                    </li>
                    <li>
                        <a href="mailto:marucci.maximo@gmail.com?subject='Hi,i saw your magento modules'" target="_blank">
                            <i class="fab fa-at"></i>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>