<?php declare(strict_types=1);
$settings = $block->getSettings();

$isEnabled = $settings['enable'];
$delay = $settings['delay'];
$content = $settings['content'];
$pagination = $settings['pagination'];
$next = $settings['next'];
$item = $settings['item'];
$loadingText = $settings['loading_text'];
$doneText = $settings['done_text'];
$loadMore = $settings['load_more'];
$loadMoreText = $settings['load_more_text'];

// ToDO: Review to customize the GIF by uploading it from backoffice
$loadingImage = $block->getViewFileUrl('images/loader-1.gif');
?>

<?php // @codingStandardsIgnoreStart ?>
<script type="text/javascript">
    require(['jquery', 'mmm/infinitescroll', 'catalogAddToCart'], function ($) {
        "use strict";
        $(document).ready(function () {
            $('body').addClass('infinitescroll');
            window.ias = $.ias({
                container: "<?= /* @noEscape */$content; ?>",
                item: "<?= /* @noEscape */$item; ?>",
                pagination: "<?= /* @noEscape */$pagination; ?>",
                next: "<?= /* @noEscape */$next; ?>",
                delay: "<?= /* @noEscape */$delay; ?>",
            });
            window.ias.extension(new IASSpinnerExtension({
                src: "<?= /* @noEscape */$loadingImage; ?>",
                html: '<div class="iass-spinner"><img src="{src}"/><span><?= /* @noEscape */$loadingText; ?></span></div>'
            }));
            window.ias.extension(new IASNoneLeftExtension({
                text: "<?= /* @noEscape */$doneText; ?>",
                html: '<div class="ias-noneleft">{text}</div>'
            }));
            window.ias.extension(new IASTriggerExtension({
                text: "<?= /* @noEscape */$loadMoreText ?>",
                html: '<div class="ias-trigger ias-trigger-next"><button class="load-more"><?= /* @noEscape */$loadMoreText ?></button></div>',
                textPrev: "<?= /* @noEscape */$loadMoreText ?>",
                htmlPrev: '<div class="ias-trigger ias-trigger-prev"><button class="load-more"><?= /* @noEscape */$loadMoreText ?></button></div>',
                offset: "<?= /* @noEscape */$loadMore ?>",
            }));
            window.ias.on('rendered', function (items) {
                $('body').trigger('contentUpdated');
                $("form[data-role='tocart-form']").catalogAddToCart();
            });
        });
    });
</script>
<?php // @codingStandardsIgnoreEnd ?>