<?php declare(strict_types=1);
$settings = $block->getSettings();

$isEnabled = $settings['enable'];
$delay = $settings['delay'];
$content = $settings['content'];
$pagination = $settings['pagination'];
$next = $settings['next'];
$item = $settings['item'];
$loadingText = $settings['loading_text'];
$doneText = $settings['done_text'];
$loadMore = $settings['load_more'];
$loadMoreText = $settings['load_more_text'];

// ToDO: Review to customize the GIF by uploading it from backoffice
$loadingImage = $this->getViewFileUrl('images/loader-1.gif');
?>

<script type="text/javascript">
    require(['jquery', 'mmm/infinitescroll', 'catalogAddToCart'], function ($) {
        "use strict";
        $(document).ready(function () {
            $('body').addClass('infinitescroll');
            window.ias = $.ias({
                container: "<?= $content; ?>",
                item: "<?= $item; ?>",
                pagination: "<?= $pagination; ?>",
                next: "<?= $next; ?>",
                delay: "<?= $delay; ?>",
            });
            window.ias.extension(new IASSpinnerExtension({
                src: "<?= $loadingImage; ?>",
                html: '<div class="iass-spinner"><img src="{src}"/><span><?= $loadingText; ?></span></div>'
            }));
            window.ias.extension(new IASNoneLeftExtension({
                text: "<?= $doneText; ?>",
                html: '<div class="ias-noneleft">{text}</div>'
            }));
            window.ias.extension(new IASTriggerExtension({
                text: "<?= $loadMoreText ?>",
                html: '<div class="ias-trigger ias-trigger-next"><button class="load-more"><?= $loadMoreText ?></button></div>',
                textPrev: "<?= $loadMoreText ?>",
                htmlPrev: '<div class="ias-trigger ias-trigger-prev"><button class="load-more"><?= $loadMoreText ?></button></div>',
                offset: "<?= $loadMore ?>",
            }));
            window.ias.on('rendered', function (items) {
                $('body').trigger('contentUpdated');
                $("form[data-role='tocart-form']").catalogAddToCart();
            });
        });
    });
</script>